[tool.black]
py38 = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | node_modules
)/
'''
[tool.isort]
profile = "black"
multi_line_output = 3
